language: python

python:
 - 3.6
 - 3.7
 - 3.8

install:
 - python -m pip install --upgrade codecov pytest-cov pytest
 - python -m pip install --upgrade pandas vincenty pyproj

script:
 - travis_wait 30 python -m pytest --cov --cov-report term-missing

after_success:
 - bash <(curl -s https://codecov.io/bash)
